edit

diff --git a/dvips b/dvips
--- a/dvips
+++ b/dvips
@@ -6,8 +6,7 @@ file=$1
 dvitype -output-level 0 $file | \
   sed -n '/^Postamble starts at byte/,${s%^Font [0-9]\+:%~/mytex/MakeTeXPK%p}' | \
   sed '/scaled/!s/$/ scaled 1000/' | sed s/scaled/$resolution/ | \
-  while read; do eval $REPLY || fail=1; done
-[ "$fail" ] && exit 1
+  { while read; do eval $REPLY || fail=1; done; [ "$fail" ]; } && exit 1
 eval "$(hexdump -s 15 -n `hexdump -s 14 -n 1 -e '/1 "%d"' $file` -v -e '/1 "%c"' $file | sed 's/.* /p=/;s/x/sp,/;s/[+-][0-9]*/sp x=& y=/')"
 export TEXCONFIG=~/dvips
 export DVIPSHEADERS=~/dvips
